const tempConf={
    addTempCon:[
        {
            name:"选择icon",
            key:"SEARCH_ICON_PIC",
            com:'upload'//上传组件
        },
        {
            name:"背景颜色",
            key:"SEARCH_BG_COLOUR",
            com:'color'//颜色选择组件
        },
        {
            name:"文本颜色",
            key:"FONT_COLOUR",
            com:'color'
        },
        {
            name:"外边框颜色",
            key:"BORDER_COLOUR",
            com:'color'
        },
        {
            name:"外边框颜色",
            key:"BORDER_COLOUR",
            com:'color'
        },
        {
            name:"提示文字",
            key:"DEFAULT_TXT",
            com:'inp'
        },
        {
            name:"搜索框长度",
            key:"LENGTH",
            com:'inp'
        },
        {
            name:"搜索框样式",
            key:"SEARCH_STYLE",
            com:'choose'//选择
        },
        {
            name:"轮播图样式",
            key:"BANNER_STYLE",
            com:'choose'
        },
        {
            name:"轮播间隔时间",
            key:"CHANGE_TIME",
            com:'inp'
        },
        {
            name:"移动点样式",
            key:"DOT_STYLE",
            com:'shape'//形状组件
        },
        {
            name:"移动点位置",
            key:"DOT_POSITION",
            com:'position'//位置组件
        },
        {
            name:"导航栏样式",
            key:"NAVIGATE_STYLE",
            com:'choose'
        },
        {
            name:"名称颜色",
            key:"NAVIGATE_COLOUR",
            com:'color'
        },
        {
            name:"每行数量",
            key:"LINE_NUMBER",
            com:'inp'
        },
        {
            name:"最大行数",
            key:"MAX_LINE",
            com:'inp'
        },
        {
            name:"更多文本颜色",
            key:"MORE_COLOUR",
            com:'color'
        },
        {
            name:"左侧图片上传",
            key:"COLUMN_LEFT_ICON_PIC",
            com:'upload'
        },
        {
            name:"右侧图片上传",
            key:"COLUMN_RIGHT_ICON_PIC",
            com:'upload'
        },
    ]
}

export default tempConf  