module.exports={
    'getSkuInfoSubList':"/gds/sku/info/getSubSkuInfo",//根据父级获取下下一集的info
    'saveSkuInfo':"/gds/sku/info/save",//添加sku属性或info
    'getSkuTypeSubList':'/gds/sku/info/getSubSkuTypes',//获取sku类型
    'infoDis':'/gds/sku/info/disable',//禁用
    "infEnable":'/gds/sku/info/enable',//启用
    'infoDel':'/gds/sku/info/delete',//删除
    "gdssavespu":"/gds/sku/info/spu",//生成spu
    "gdssavegoods":"/gds/sku/info/goods",//生成商品
    "gdssavegoodsgroup":"/gds/sku/info/goodsgroup",//生成商品组
}